### ISSUE TITLE
[IaC] Terraform CI/CD設定

### ISSUE THREAD

**Issue by KJR020** [KJR020/picture-book-explorer#20]
## CI/CD設定

- [ ] GitHub Actions設定
  ```yaml
  name: Terraform
  on:
    pull_request:
      paths:
        - 'terraform/**'
    push:
      branches:
        - main
      paths:
        - 'terraform/**'
  ```

- [ ] ワークフロー定義
  - Plan（PR時）
  - Apply（マージ時）
  - 環境別デプロイ

## セキュリティ
- [ ] GitHub Secretsの設定
- [ ] OIDC認証設定
- [ ] 承認フロー実装
