### ISSUE TITLE
[Dev] ローカル開発環境のDocker化

### ISSUE THREAD

**Issue by KJR020** [KJR020/picture-book-explorer#21]
### Docker Compose設定
```yaml
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: book_explorer
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

volumes:
  mysql-data:
  minio-data:
```

### タスク
- [ ] Docker Compose設定
- [ ] ローカルDB設定
- [ ] MinIO（S3互換）設定
- [ ] 環境変数設定
- [ ] 開発用シードデータ作成
- [ ] ドキュメント作成
